config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/users'
    get 'admin/build_orders'
    get 'admin/attack_benchmarks'
  end

  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'static_pages#landing'

  # static page routes
  get 'landing', to: 'static_pages#landing', as: :landing
  get 'about', to: 'static_pages#about', as: :about

  # user routes with scoped resources
  resources :users, only: [:show] do
    resources :build_orders
    resources :attack_benchmarks
  end

  get 'users/:id/account_info', to: 'users#account_info', as: :show_account_info

  # routes for adding and deleting build order steps
  resources :build_order_steps, only: [], param: :index do
    member do
      delete '(:id)' => "build_order_steps#destroy", as: ""
      post '/' => "build_order_steps#create"
    end
  end

  # routes for adding and deleting benchmark units
  resources :units, only: [], param: :index do
    member do
      delete '(:id)' => "units#destroy", as: ""
      post '/' => "units#create"
    end
  end
end

app/models/build_order.rb
class BuildOrder < ApplicationRecord
  belongs_to :user
  has_many :build_order_steps, dependent: :destroy
  accepts_nested_attributes_for :build_order_steps,
    reject_if: :all_blank, allow_destroy: true
  validates :name, :faction, presence: true

  def self.search(user, params)
    params[:query].blank? ? user.build_orders.all : user.build_orders.where(
      "name LIKE ?", "%#{sanitize_sql_like(params[:query])}%"
    )
  end
end

app/controllers/build_orders_controller.rb
class BuildOrdersController < ApplicationController
    load_and_authorize_resource :user
    load_and_authorize_resource :build_order, through: :user
  
    def index
      @build_orders = BuildOrder.search(@user, params).page(params[:page]).per(10)
    end
  
    def show
    end
  
    def new
      @build_order.build_order_steps.build
    end
  
    def edit
    end
  
    def create
      respond_to do |format|
        if @build_order.save
          flash[:notice] = 'Build order saved'
          format.html { redirect_to controller: 'build_orders', action: 'show', id: @build_order.id, user_id: @build_order.user_id }
        else
          flash.now[:alert] = 'Could not save build order'
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @build_order.update(build_order_params)
          flash[:notice] = 'Build order updated'
          format.html { redirect_to controller: 'build_orders', action: 'show', id: @build_order.id, user_id: @build_order.user_id }
        else
          flash.now[:alert] = 'Could not update build order'
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @build_order.destroy
  
      respond_to do |format|
        format.html { redirect_to user_build_orders_path(user_id: current_user.id), notice: 'Build order was destroyed' }
      end
    end
  
    private
  
      # Only allow a list of trusted parameters through
      def build_order_params
        params.require(:build_order).permit(
          :name,
          :faction,
          :notes,
          build_order_steps_attributes: [:id, :supply, :unit, :description, :_destroy]
        )
      end
  end
  

app/views/build_orders/_build_order.html.erb
<div class="container-md my-4 p-3 bg-body-secondary rounded-4 border-orange">
  <div id="<%= dom_id build_order %>">
    <h1 class="text-center"><%= build_order.name %></h1>
    <hr/>
    <p class="fs-3"><strong>Faction:</strong> <%= build_order.faction %></p>
    <hr/>
    <div class="accordion accordion-flush mb-4" id="buildOrderDetails_<%= build_order.id %>">
      <div class="accordion-item">
        <h2 class="accordion-header" id="heading_<%= build_order.id %>">
          <button class="accordion-button collapsed fs-4" type="button" data-bs-toggle="collapse"
           data-bs-target="#collapse_<%= build_order.id %>" aria-expanded="false" aria-controls="collapse_<%= build_order.id %>">Details</button>
        </h2>
        <div id="collapse_<%= build_order.id %>" class="accordion-collapse collapse" data-bs-parent="#buildOrderDetails_<%= build_order.id %>"
         aria-labelledby="heading_<%= build_order.id %>">
          <div class="accordion-body">
            <p class="fs-3"><strong>Notes:</strong></p>
            <p class="fs-4"><%= build_order.notes %></p>
            <hr/>
            <p class="fs-3"><strong>Steps:</strong></p>
            <div class="table-responsive">
              <table class="table table-striped table-bordered table-dark">
                <thead>
                  <tr>
                    <th class="fs-5" scope="col">#</th>
                    <th class="fs-5" scope="col">Supply</th>
                    <th class="fs-5" scope="col">Unit</th>
                    <th class="fs-5" scope="col">Description</th>
                  </tr>
                </thead>
                <tbody>
                  <% build_order.build_order_steps.each_with_index do |step, idx| %>
                    <tr>
                      <th class="fs-5" scope="row"><%= idx + 1 %></th>
                      <td class="fs-5"><%= step.supply %></td>
                      <td class="fs-5"><%= step.unit %></td>
                      <td class="fs-5"><%= step.description %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <hr/>
            <% if cannot? :manage, build_order %>
              <p class="fs-3"><strong>Created by:</strong> <%= build_order.user.username %></p>
              <hr/>
            <% end %>
          </div>
        </div>
      </div> 
    </div>
    <% if current_page?(controller: "build_orders", action: "index") %>
      <span style="margin-right: 10px"><%= link_to "Show", user_build_order_path(@user, build_order), class: "fs-6" %></span>
    <% end %>
    <% if can? :manage, build_order %>
      <span style="margin-right: 10px"><%= link_to 'Edit', edit_user_build_order_path(@user, build_order), class: "fs-6" %></span>
      <%= link_to 'Delete', user_build_order_path(@user, build_order), class: "fs-6", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    <% end %>    
  </div>
</div>

app/views/build_orders/_form.html.erb
<div class="container-fluid my-5">
  <div class="container-md p-3 bg-body-secondary rounded-4 border-orange">
    <%= form_with model: [@user, @build_order], local: true do |form| %>
      <% if build_order.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(build_order.errors.count, "error") %> prohibited this build_order from being saved:</h2>

          <ul>
            <% build_order.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name, style: "display: block", class: "fs-3" %>
        <%= form.text_field :name, class: "form-control form-control-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :faction, style: "display: block", class: "fs-3" %>
        <%= form.select :faction, ['Resistance', 'Infernals'], {}, class: "form-control form-control-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :notes, style: "display: block", class: "fs-3" %>
        <%= form.text_area :notes, class: "form-control form-control-lg" %>
      </div>
      <hr/>

      <h2>Steps</h2>
      <div id="steps">
        <%= form.fields_for :build_order_steps do |step_form| %>
          <%= render "build_order_steps/form", form: step_form %>
        <% end %>
      </div>

      <%= form.submit "Add step",
        class: "btn btn-primary my-2",
        formaction: build_order_step_path(@build_order.build_order_steps.size),
        formmethod: :post,
        formnovalidate: true,
        id: "add-build-order-step" %>

      <div>
        <% if params[:action] == 'new' || params[:action] == 'create' %>
          <%= form.submit "Create build order", class: "btn btn-success my-2" %>
        <% else %>
          <%= form.submit "Update build order", class: "btn btn-success my-2" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/build_orders/edit.html.erb
<% provide(:title, "#{@user.username} | Build Orders | #{@build_order.name} | Edit") %>

<div class="m-4"><%= link_to "Back to build orders", user_build_orders_path(@user) %></div>

<h1 class="mt-4 display-4 text-center">Edit build order</h1>

<%= render "form", build_order: @build_order %>

app/views/build_orders/index.html.erb
<% provide(:title, "#{@user.username} | Build Orders") %>

<% if @user == current_user %>
  <div class="m-4"><%= link_to "New build order", new_user_build_order_path(@user) %></div>
<% end %>

<h1 class="mt-4 display-4 text-center">Build orders | <%= @user.username %></h1>

<div class="container-fluid my-5">
  <div class="container-md p-0">
    <%= form_tag user_build_orders_path(user_id: @user.id), method: :get,
     data: { turbo_frame: "search-results", turbo_action: "advance", controller: "search",
     action: "input->search#submit" } do |f| %>
      <%= text_field_tag "query", existing_input(:query), placeholder: "Search by title ...", class: "form-control my-2 me-2" %>
      <%= submit_tag "Search", class: "btn btn-success my-2 me-2" %>
    <% end %>
  </div>
  
  <div id="build_orders">
    <%= turbo_frame_tag "search-results", target: "_top" do %>
      <%= paginate @build_orders, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
        <% @build_orders.each do |build_order| %>
          <%= render build_order %>
        <% end %>
      <%= paginate @build_orders, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
    <% end %>
  </div>
</div>

app/views/build_orders/new.html.erb
<% provide(:title, "#{@user.username} | Build Orders | New") %>

<div class="m-4"><%= link_to "Back to build orders", user_build_orders_path(@user) %></div>

<h1 class="mt-4 display-4 text-center">New build order</h1>

<%= render "form", build_order: @build_order %>

app/views/build_orders/show.html.erb
<% provide(:title, "#{@user.username} | Build Orders | #{@build_order.name}") %>

<div class="m-4"><%= link_to 'Back to build orders', user_build_orders_path(@user) %></div>

<div class="container-fluid my-5">
    <%= render @build_order %>
</div>