config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/users'
    get 'admin/build_orders'
    get 'admin/attack_benchmarks'
  end

  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'static_pages#landing'

  # static page routes
  get 'landing', to: 'static_pages#landing', as: :landing
  get 'about', to: 'static_pages#about', as: :about

  # user routes with scoped resources
  resources :users, only: [:show] do
    resources :build_orders
    resources :attack_benchmarks
  end

  get 'users/:id/account_info', to: 'users#account_info', as: :show_account_info

  # routes for adding and deleting build order steps
  resources :build_order_steps, only: [], param: :index do
    member do
      delete '(:id)' => "build_order_steps#destroy", as: ""
      post '/' => "build_order_steps#create"
    end
  end

  # routes for adding and deleting benchmark units
  resources :units, only: [], param: :index do
    member do
      delete '(:id)' => "units#destroy", as: ""
      post '/' => "units#create"
    end
  end
end

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class:'btn btn-outline-primary admin-button' %>

app/views/admin/_nav_links.html.erb
<div class="container text-center">
    <p>
        <%= link_to 'Admin', admin_path %><%= " > #{params[:action].capitalize}" unless params[:action].eql?("index") %>
    </p>
    <div class="btn-group flex-wrap gap-3 mb-5">
        <%= render "admin/link", resource: User %>
        <%= render "admin/link", resource: BuildOrder %>
        <%= render "admin/link", resource: AttackBenchmark %>
    </div>
</div>

app/views/admin/attack_benchmarks.html.erb
<% provide(:title, "Admin | Attack Benchmarks") %>

<div class="container my-5">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
    <div class="table-responsive">
        <%= paginate @attack_benchmarks, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
        <table class="table table-responsive table-dark table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">User</th>
                    <th scope="col">Created On</th>
                </tr>
            </thead>
            <tbody>
                <% @attack_benchmarks.each do |attack_benchmark| %>
                    <tr>
                        <th scope="row"><%= link_to attack_benchmark.id, user_attack_benchmark_path(attack_benchmark.user, attack_benchmark) %></th>
                        <td><%= link_to attack_benchmark.user.username, user_path(attack_benchmark.user) %></td>
                        <td><%= attack_benchmark.created_at.strftime("%m/%d/%Y") %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= paginate @attack_benchmarks, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
    </div>
</div>

app/views/admin/build_orders.html.erb
<% provide(:title, "Admin | Build Orders") %>

<div class="container my-5">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
    <div class="table-responsive">
        <%= paginate @build_orders, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
        <table class="table table-responsive table-dark table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">User</th>
                    <th scope="col">Created On</th>
                </tr>
            </thead>
            <tbody>
                <% @build_orders.each do |build_order| %>
                    <tr>
                        <th scope="row"><%= link_to build_order.id, user_build_order_path(build_order.user, build_order) %></th>
                        <td><%= build_order.name %></td>
                        <td><%= link_to build_order.user.username, user_path(build_order.user) %></td>
                        <td><%= build_order.created_at.strftime("%m/%d/%Y") %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= paginate @build_orders, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
    </div>
</div>

app/views/admin/index.html.erb
<% provide(:title, "Admin | Index") %>

<div class="container my-5">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
</div>

app/views/admin/users.html.erb
<% provide(:title, "Admin | Users") %>

<div class="container my-5">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
    <div class="table-responsive">
        <%= paginate @users, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
        <table class="table table-responsive table-dark table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Username</th>
                    <th scope="col">Email</th>
                    <th scope="col">Created On</th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <th scope="row"><%= user.id %></th>
                        <td><%= link_to user.username, user_path(user) %></td>
                        <td><%= user.email %></td>
                        <td><%= user.created_at.strftime("%m/%d/%Y") %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <%= paginate @users, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
    </div>
</div>