config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/users'
    get 'admin/build_orders'
    get 'admin/attack_benchmarks'
  end

  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'static_pages#landing'

  # static page routes
  get 'landing', to: 'static_pages#landing', as: :landing
  get 'about', to: 'static_pages#about', as: :about

  # user routes with scoped resources
  resources :users, only: [:show] do
    resources :build_orders
    resources :attack_benchmarks
  end

  get 'users/:id/account_info', to: 'users#account_info', as: :show_account_info

  # routes for adding and deleting build order steps
  resources :build_order_steps, only: [], param: :index do
    member do
      delete '(:id)' => "build_order_steps#destroy", as: ""
      post '/' => "build_order_steps#create"
    end
  end

  # routes for adding and deleting benchmark units
  resources :units, only: [], param: :index do
    member do
      delete '(:id)' => "units#destroy", as: ""
      post '/' => "units#create"
    end
  end
end

app/models/attack_benchmark.rb
class AttackBenchmark < ApplicationRecord
  belongs_to :user
  has_many :units, dependent: :destroy
  accepts_nested_attributes_for :units,
    reject_if: :all_blank, allow_destroy: true
  validates :map, presence: true

  # formats time attribute into string
  def formatted_time
    time.min.to_s + ":" + time.sec.to_s.rjust(2, '0')
  end

  # formats data attribute into string
  def formatted_date
    created_at.strftime("%m/%d/%Y")
  end

  def self.search(user, params)
    if params[:query].blank?
      db_query = user.attack_benchmarks.all
    else
      criteria = format_search_criteria(params[:search_criteria])
      db_query = user.attack_benchmarks.where("#{criteria} LIKE ?",
        AttackBenchmark.sanitize_sql_like(params[:query]) + "%"
      )
    end

    if !params[:date_from].blank? && !params[:date_to].blank?
      date_from = DateTime.strptime(params[:date_from], '%Y-%m-%d')
      date_to = DateTime.strptime(params[:date_to], '%Y-%m-%d')
      db_query = db_query.where(created_at: (date_from.beginning_of_day..date_to.end_of_day))
    end

    db_query.order(created_at: :desc)
  end

  private

    # helper for search method
    def self.format_search_criteria(str)
      output = ""
      str.each_char do |char|
        char = "_" if char == " "

        output += char
      end
      output
    end

end

app/controllers/attack_benchmarks_controller.rb
class AttackBenchmarksController < ApplicationController
    load_and_authorize_resource :user
    load_and_authorize_resource :attack_benchmark, through: :user
  
    # GET /attack_benchmarks or /attack_benchmarks.json
    def index
      @attack_benchmarks = AttackBenchmark.search(@user, params).page(params[:page]).per(10)
    end
  
    # GET /attack_benchmarks/1 or /attack_benchmarks/1.json
    def show
    end
  
    # GET /attack_benchmarks/new
    def new
      @attack_benchmark.units.build
    end
  
    # GET /attack_benchmarks/1/edit
    def edit
    end
  
    # POST /attack_benchmarks or /attack_benchmarks.json
    def create
      respond_to do |format|
        if @attack_benchmark.save
          flash[:notice] = 'Benchmark saved'
          format.html { redirect_to controller: 'attack_benchmarks', action: 'show', id: @attack_benchmark.id, user_id: @attack_benchmark.user_id }
        else
          flash.now[:alert] = 'Could not save benchmark'
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @attack_benchmark.update(attack_benchmark_params)
          flash[:notice] = 'Benchmark updated'
          format.html { redirect_to controller: 'attack_benchmarks', action: 'show', id: @attack_benchmark.id, user_id: @attack_benchmark.user_id }
        else
          flash.now[:alert] = 'Could not update benchmark'
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @attack_benchmark.destroy
  
      respond_to do |format|
        format.html { redirect_to user_attack_benchmarks_path(user_id: current_user.id), notice: 'Benchmark was destroyed' }
      end
    end
  
    private
    
      # Only allow a list of trusted parameters through.
      def attack_benchmark_params
        params.require(:attack_benchmark).permit(
          :build_order,
          :time,
          :map,
          :notes,
          :match_outcome,
          units_attributes: [:id, :unit_type, :quantity, :_destroy]
        )
      end
end

app/views/attack_benchmarks/_attack_benchmark.html.erb
<div class="container-md my-4 p-3 bg-body-secondary rounded-4 border-orange">
  <div id="<%= dom_id attack_benchmark %>">
    <h1 class="text-center"><%= attack_benchmark.build_order + ' - ' + attack_benchmark.formatted_date %></h1>
    <hr/>
    <p class="fs-3"><strong>Time of attack:</strong> <%= attack_benchmark.formatted_time %> minutes</p>
    <hr/>
    <p class="fs-3"><strong>Map:</strong> <%= attack_benchmark.map %></p>
    <hr/>
    <div class="accordion accordion-flush mb-4" id="attackBenchmarkDetails_<%= attack_benchmark.id %>">
      <div class="accordion-item">
        <h2 class="accordion-header" id="heading_<%= attack_benchmark.id %>">
          <button class="accordion-button collapsed fs-4" type="button" data-bs-toggle="collapse"
           data-bs-target="#collapse_<%= attack_benchmark.id %>" aria-expanded="false" aria-controls="collapse_<%= attack_benchmark.id %>">Details</button>
        </h2>
        <div id="collapse_<%= attack_benchmark.id %>" class="accordion-collapse collapse" data-bs-parent="#attackBenchmarkDetails_<%= attack_benchmark.id %>"
         aria-labelledby="heading_<%= attack_benchmark.id %>">
          <div class="accordion-body">
            <p class="fs-3"><strong>Match outcome:</strong> <%= attack_benchmark.match_outcome %></p>
            <hr/>
            <p class="fs-3"><strong>Notes:</strong></p>
            <p class="fs-4"><%= attack_benchmark.notes %></p>
            <hr/>
            <p class="fs-3"><strong>Units:</strong></p>
            <div class="table-responsive">
              <table class="table table-striped table-bordered table-dark">
                <thead>
                  <tr>
                    <th class="fs-5" scope="col">Unit</th>
                    <th class="fs-5" scope="col">Quantity</th>
                  </tr>
                </thead>
                <tbody>
                  <% attack_benchmark.units.each do |unit| %>
                    <tr>
                      <td class="fs-5"><%= unit.unit_type %></td>
                      <td class="fs-5"><%= unit.quantity %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <hr>
            <% if cannot? :manage, attack_benchmark %>
              <p class="fs-3"><strong>Created by:</strong> <%= attack_benchmark.user.username %></p>
              <hr/>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% if current_page?(controller: "attack_benchmarks", action: "index") %>
      <span style="margin-right: 10px"><%= link_to "Show", user_attack_benchmark_path(@user, attack_benchmark), class: "fs-6" %></span>
    <% end %>
    <% if can? :manage, attack_benchmark %>
      <span style="margin-right: 10px"><%= link_to 'Edit', edit_user_attack_benchmark_path(@user, attack_benchmark), class: "fs-6" %></span>
      <%= link_to 'Delete', user_attack_benchmark_path(@user, attack_benchmark), class: "fs-6", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

app/views/attack_benchmarks/_form.html.erb
<div class="container-fluid my-5">
  <div class="container-md p-3 bg-body-secondary rounded-4 border-orange">
    <%= form_with model: [@user, @attack_benchmark], local: true do |form| %>
      <% if attack_benchmark.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(attack_benchmark.errors.count, "error") %> prohibited this benchmark from being saved:</h2>
  
          <ul>
            <% attack_benchmark.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :build_order, style: "display: block", class: "fs-3" %>
        <%= form.select :build_order, @user.build_orders.map { |bo| bo.name }, {}, class: "form-control form-control-lg" %>
      </div>
  
      <div class="form-row">
          <%= form.label :time, style: "display: block", class: "fs-3" %>
  
          <!-- Time separator is used here to wrap minute and seconds time selects with a div for bootstrap styling purposes -->
          <div class="form-group col-6 pe-1 inline-block">
            <%= form.time_select :time, { discard_hour: true, include_seconds: true, prompt: true, time_separator: "</div><div class='form-group col-6 ps-1 inline-block'>" }, class: "form-control form-control-lg" %>
          </div>
      </div>
  
      <div class="form-group">
        <%= form.label :map, style: "display: block", class: "fs-3" %>
        <%= form.text_field :map, class: "form-control form-control-lg" %>
      </div>

      <div class="form-group">
        <%= form.label :match_outcome, style: "display: block", class: "fs-3" %>
        <%= form.select :match_outcome, ['Win', 'Loss', 'Tie'], {}, class: "form-control form-control-lg" %>
      </div>
  
      <div class="form-group">
        <%= form.label :notes, style: "display: block", class: "fs-3" %>
        <%= form.text_area :notes, class: "form-control form-control-lg" %>
      </div>
      <hr/>

      <h2>Units</h2>
      <div id="units">
        <%= form.fields_for :units do |unit_form| %>
          <%= render "units/form", form: unit_form %>
        <% end %>      
      </div>

      <%= form.submit "Add unit",
          class: "btn btn-primary my-2",
          formaction: unit_path(@attack_benchmark.units.size),
          formmethod: :post,
          formnovalidate: true,
          id: "add-unit" %>
  
      <div>
        <% if params[:action] == 'new' || params[:action] == 'create' %>
          <%= form.submit "Create benchmark", class: "btn btn-success my-2" %>
        <% else %>
          <%= form.submit "Update benchmark", class: "btn btn-success my-2" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/attack_benchmarks/edit.html.erb
<% provide(:title, "#{@user.username} | Benchmarks | #{@attack_benchmark.id} | Edit") %>

<div class="m-4"><%= link_to "Back to benchmarks", user_attack_benchmarks_path(@user) %></div>

<h1 class="mt-4 display-4 text-center">Edit benchmark</h1>

<%= render "form", attack_benchmark: @attack_benchmark %>

app/views/attack_benchmarks/index.html.erb
<% provide(:title, "#{@user.username} | Benchmarks") %>

<% if @user == current_user %>
  <div class="m-4"><%= link_to "New benchmark", new_user_attack_benchmark_path(@user) %></div>
<% end %>

<h1 class="mt-4 display-4 text-center">Benchmarks | <%= @user.username %></h1>

<div class="container-fluid my-5">
  <div class="container-md p-0">
    <%= form_tag user_attack_benchmarks_path(user_id: @user.id), method: :get,
     data: { turbo_frame: "search-results", turbo_action: "advance", controller: "search",
     action: "input->search#submit" } do |f| %>
      <%= text_field_tag "query", existing_input(:query), placeholder: "Search ...", class: "form-control my-2 me-2" %>
      
      <div class="form-group">
        <%= label_tag "Search by" %>:
        <%= select_tag "search_criteria", options_for_select(%w[ build\ order map match\ outcome ], existing_input(:search_criteria)), class: "form-control my-2" %>
      </div>

      <div class="row g-3">
        <div class="form-group col-md-6">
          <%= label_tag "From" %>:
          <%= date_field_tag "date_from", existing_input(:date_from), class: "form-control my-2" %>
        </div>
        <div class="form-group col-md-6">
          <%= label_tag "To" %>:
          <%= date_field_tag "date_to", existing_input(:date_to), class: "form-control my-2" %>
        </div>
      </div>
      
      <%= submit_tag "Search", class: "btn btn-success my-2" %>
    <% end %>
  </div>

  <div id="attack_benchmarks">
    <%= turbo_frame_tag "search-results", target: "_top" do %>
      <%= paginate @attack_benchmarks, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
      <% @attack_benchmarks.each do |attack_benchmark| %>
        <%= render attack_benchmark %>
      <% end %>
      <%= paginate @attack_benchmarks, theme: 'bootstrap-5', pagination_class: 'flex-wrap justify-content-center' %>
    <% end %>
  </div>
  
</div>

app/views/attack_benchmarks/new.html.erb
<% provide(:title, "#{@user.username} | Benchmarks | New") %>

<div class="m-4"><%= link_to "Back to benchmarks", user_attack_benchmarks_path(@user) %></div>

<h1 class="mt-4 display-4 text-center">New benchmark</h1>

<%= render "form", attack_benchmark: @attack_benchmark %>

app/views/attack_benchmarks/show.html.erb
<% provide(:title, "#{@user.username} | Benchmarks | #{@attack_benchmark.id}") %>

<div class="m-4"><%= link_to 'Back to benchmarks', user_attack_benchmarks_path(@user) %></div>

<div class="container-fluid my-5">
    <%= render @attack_benchmark %>
</div>