config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/users'
    get 'admin/build_orders'
    get 'admin/attack_benchmarks'
  end

  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'static_pages#landing'

  # static page routes
  get 'landing', to: 'static_pages#landing', as: :landing
  get 'about', to: 'static_pages#about', as: :about

  # user routes with scoped resources
  resources :users, only: [:show] do
    resources :build_orders
    resources :attack_benchmarks
  end

  get 'users/:id/account_info', to: 'users#account_info', as: :show_account_info

  # routes for adding and deleting build order steps
  resources :build_order_steps, only: [], param: :index do
    member do
      delete '(:id)' => "build_order_steps#destroy", as: ""
      post '/' => "build_order_steps#create"
    end
  end

  # routes for adding and deleting benchmark units
  resources :units, only: [], param: :index do
    member do
      delete '(:id)' => "units#destroy", as: ""
      post '/' => "units#create"
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav-links" aria-controls="nav-links" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="nav-links" class="collapse navbar-collapse justify-content-end">
            <ul class="nav navbar-nav mr-4">
                <li class="nav-item"><%= link_to 'About', about_path, :class => "nav-link" %></li>
                <% if user_signed_in? %>
                    <li><%= link_to 'Admin Dashboard', admin_path, :class => "nav-link" if current_user.admin? %></li>
                    <li class="nav-item"><%= link_to 'Home', user_path(current_user), :class => "nav-link" %></li>
                    <li class="nav-item"><%= link_to 'Account', show_account_info_path(current_user), :class => "nav-link"  %></li>
                    <li class="nav-item"><%= link_to 'Log Out', destroy_user_session_path, data: { "turbo-method": :delete }, :class => "nav-link" %></li>
                <% else %>                    
                    <li class="nav-item"><%= link_to 'Log In', user_session_path, :class => "nav-link" %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title>SgBenchmarker | <%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% unless notice.nil? %>
      <div class="d-flex align-items-center justify-content-between alert notice alert-dismissable fade show p-3 fs-4 text-light">
        <div class="d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" aria-label="Notice:">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
          </svg>
          <div><strong><%= notice %></strong></div>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% unless alert.nil? %>
      <div class="d-flex align-items-center justify-content-between alert warning alert-dismissable fade show p-3 fs-4 text-light">
        <div class="d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" aria-label="Alert:">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
          </svg>
          <div><strong><%= alert %></strong></div>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>        
      </div>
    <% end %>
    <div class="container-fluid p-0">
      <%= yield %>
    </div>
  </body>
</html>